
[types]

	[types.wood_type]

		[types.wood_type.domum_ornamentum]
			cactus = true
			cactus_extra = true

		[types.wood_type.ars_nouveau]
			archwood = true

		[types.wood_type.quark]
			bamboo = true
			azalea = true
			blossom = true
			ancient = true

		[types.wood_type.ecologics]
			flowering_azalea = true
			azalea = true
			coconut = true
			walnut = true

		[types.wood_type.iter_rpg]
			sacred = true

		[types.wood_type.botania]
			livingwood = true
			dreamwood = true

		[types.wood_type.abundant_atmosphere]
			ash = true
			gourdrot = true

		[types.wood_type.theabyss]
			blaru = true
			jungle = true
			slimed = true
			frozen = true
			vigilant = true

		[types.wood_type.hexerei]
			mahogany = true
			willow = true
			witch_hazel = true

		[types.wood_type.twilightforest]
			twilight_oak = true
			canopy = true
			mangrove = true
			dark = true
			time = true
			transformation = true
			mining = true
			sorting = true

		[types.wood_type.undergarden]
			smogstem = true
			wigglewood = true
			grongle = true

		[types.wood_type.regions_unexplored]
			alpha = true
			baobab = true
			blackwood = true
			cherry = true
			cypress = true
			dead = true
			eucalyptus = true
			joshua = true
			larch = true
			maple = true
			mauve = true
			palm = true
			pine = true
			redwood = true
			willow = true
			sculkwood = true

		[types.wood_type.upgrade_aquatic]
			driftwood = true
			river = true

		[types.wood_type.habitat]
			fairy_ring_mushroom = true

		[types.wood_type.colorfulazaleas]
			tecal_azalea = true
			fiss_azalea = true
			roze_azalea = true
			azule_azalea = true
			bright_azalea = true
			walnut_azalea = true
			titanium_azalea = true

		[types.wood_type.integrateddynamics]
			menril = true

	[types.leaves_type]

		[types.leaves_type.ars_nouveau]
			blue_archwood = true
			green_archwood = true
			purple_archwood = true
			red_archwood = true

		[types.leaves_type.regions_unexplored]
			bamboo = true
			golden_larch = true
			alpha = true
			apple_oak = true
			flowering = true
			silver_birch = true
			baobab = true
			blackwood = true
			cherry = true
			red_cherry = true
			pink_cherry = true
			white_cherry = true
			cypress = true
			dead = true
			dead_pine = true
			eucalyptus = true
			larch = true
			maple = true
			red_maple = true
			orange_maple = true
			mauve = true
			palm = true
			pine = true
			redwood = true
			willow = true
			sculkwood = true

		[types.leaves_type.twilightforest]
			beanstalk = true
			thorn = true
			twilight_oak = true
			canopy = true
			mangrove = true
			dark = true
			rainbow_oak = true
			time = true
			transformation = true
			mining = true
			sorting = true

		[types.leaves_type.iter_rpg]
			sacred = true

		[types.leaves_type.abundant_atmosphere]
			ash = true
			gourdrot = true

		[types.leaves_type.ecologics]
			coconut = true
			walnut = true

		[types.leaves_type.hexerei]
			mahogany = true
			willow = true
			witch_hazel = true

		[types.leaves_type.undergarden]
			smogstem = true
			wigglewood = true
			grongle = true

		[types.leaves_type.quark]
			blue_blossom = true
			lavender_blossom = true
			orange_blossom = true
			pink_blossom = true
			yellow_blossom = true
			red_blossom = true
			ancient = true

		[types.leaves_type.upgrade_aquatic]
			river = true

		[types.leaves_type.colorfulazaleas]
			blue_azalea = true
			blue_blooming_azalea = true
			blue_flowering_azalea = true
			orange_azalea = true
			orange_blooming_azalea = true
			orange_flowering_azalea = true
			pink_azalea = true
			pink_blooming_azalea = true
			pink_flowering_azalea = true
			purple_azalea = true
			purple_blooming_azalea = true
			purple_flowering_azalea = true
			red_azalea = true
			red_blooming_azalea = true
			red_flowering_azalea = true
			white_azalea = true
			white_blooming_azalea = true
			white_flowering_azalea = true
			yellow_azalea = true
			yellow_blooming_azalea = true
			yellow_flowering_azalea = true

		[types.leaves_type.integrateddynamics]
			menril = true

[entries]

	[entries.wood_type]

		[entries.wood_type.twilightforest]
			hollow_log_horizontal = true
			hollow_log_vertical = true
			banister = true
			hollow_log_climbable = true

		[entries.wood_type.storagedrawers]
			trim = true
			full_drawers_2 = true
			half_drawers_1 = true
			full_drawers_4 = true
			half_drawers_4 = true
			half_drawers_2 = true
			full_drawers_1 = true

		[entries.wood_type.decorative_blocks]
			beam = true
			support = true
			seat = true
			palisade = true

		[entries.wood_type.create]
			window = true
			window_pane = true

		[entries.wood_type.farmersdelight]
			cabinet = true

		[entries.wood_type.quark]
			hollow_log = true
			vertical_planks = true
			post = true
			trapped_chest = true
			bookshelf = true
			chest = true
			stripped_post = true
			ladder = true

	[entries.leaves_type]

		[entries.leaves_type.quark]
			hedge = true
			leaf_carpet = true

