
["Loot Config"]
	#The probability for a Miner's Tool Bags to be dropped when mining a valid block (this number is divided by 10.000, so 100=1%)
	toolbag_drop_classic_proba = 0.0
	#The probability for a Miner's Tool Bags to be dropped when mining a valid block in a biome registered in the list of biomes dropping more frequently specific bags (this number is divided by 10.000, so 100=1%)
	toolbag_drop_buffed_proba = 0.0
	#The probability for a Miner's Plant Bags to be dropped when mining a valid block (this number is divided by 10.000, so 100=1%)
	plantbag_drop_classic_proba = 0.0
	#The probability for a Miner's Plants Bags to be dropped when mining a valid block in a biome registered in the list of biomes dropping more frequently specific bags (this number is divided by 10.000, so 100=1%)
	plantbag_drop_buffed_proba = 0.0
	#The probability for a Miner's Treasure Bags to be dropped when mining a valid block (this number is divided by 10.000, so 100=1%)
	treasurebag_drop_classic_proba = 0.0
	#The probability for a Miner's Treasure Bags to be dropped when mining a valid block in a biome registered in the list of biomes dropping more frequently specific bags (this number is divided by 10.000, so 100=1%)
	treasurebag_drop_buffed_proba = 0.0

[Items]
	#If an item is set to false, the player will get more additional items (iron ingots for the tool bag, glow berries for the plants bag, disc fragment for the treasure bag)
	sword_of_the_depths = true
	fiery_pickaxe = true
	sharp_iron_pickaxe = true
	climbing_axe = true
	#---
	glowing_spore = true
	ancient_seed = true
	yellow_mushroom = true
	strange_root = true
	#---
	broken_clock = false
	bat_talisman = true
	spider_amulet = true
	golden_cube = false

